version: "3"
services:
  webserver:
    tty: true # Enables debugging capabilities when attached to this container.
    image: 'docker.io/ofirsh11/worldoffames'
    container_name: flask_server
    ports:
      - 8777:8777
    volumes:
      - .:/app

    
