version: '3'

services:
  python:
    tty: true # Enables debugging capabilities when attached to this container.
    image: 'docker.io/ofirsh11/worldoffames'
    ports:
      - 8777:8777
    volumes:
      - .:/tmp